version: '2.1'
services:
  singletonservice:
    image: singletonservice
    build: ./
    restart: always
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"