eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/discovery-1.0/
server:
  port: 8080

mybatisdb:
  filters: stat
  initialSize: 1
  maxActive: 5
  minIdle: 1
  maxWait: 30000
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 300000
  validationQuery:  "SELECT 1 FROM DUAL"
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 1
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: true
  url: jdbc:oracle:thin:@140.86.0.30:1521:ORCL
  username: customs
  password: Welcome1
  logSlowSql: false
  slowSqlMillis: 1000
  mergeSql: false